"""Structural guard for the Operator export-lowering doc correction (neograph-03djs).

neograph-03djs's deliverable is a DOCUMENTATION CORRECTION -- no runtime-observable
behavior, no code changes. Per the test-author protocol's structural-disease
exception, this guard pins the doc CONTENT across the four target files instead
of a behavioral contract:

  - docs/design/agent-spec-api/02-flows-nodes.md (:22, :132-137)
  - docs/design/agent-spec-api/00-master-synthesis.md (:78)
  - docs/design/agent-spec-interop-2026-07-09.md (:174)
  - docs/design/agent-spec-api/14-adapters.md (:142)

The corrected wording (design step 2, refined per architect review MEDIUM
finding) replaces the stale "BranchingNode / gated edge (exact lowering TBD)"
claim with the VERIFIED composite:

    BranchingNode(mapping={<condition-string>: PAUSE_BRANCH})
    + ControlFlowEdge(from_branch=PAUSE_BRANCH) -> InputMessageNode
    + ControlFlowEdge(from_branch=DEFAULT_BRANCH) -> reconverge

...and must NOT ship "zero extra plumbing" framing -- the boolean-to-string-key
coercion obligation (Operator.when yields a Python truthy value; BranchingNode's
mapping keys are literal strings) must be stated explicitly near the
Operator/BranchingNode correction, or the composite would silently always take
the bypass branch and never pause -- a fail-soft degradation.

docs/design/agent-spec-ratification-2026-07-13.md is explicitly OUT of scope
(design step 4: "Do NOT edit" -- it's a historical decision record) and is
therefore not part of the corrected-files list this guard checks.

This is TDD red: the four docs still carry the stale "exact lowering TBD" /
"gated edge (exact lowering TBD" language (neograph-u7gy8.23 -- Implement --
is still OPEN), so every test in this module currently FAILS.
"""

from __future__ import annotations

import pathlib

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

FLOWS_NODES_PATH = REPO_ROOT / "docs" / "design" / "agent-spec-api" / "02-flows-nodes.md"
MASTER_SYNTHESIS_PATH = REPO_ROOT / "docs" / "design" / "agent-spec-api" / "00-master-synthesis.md"
INTEROP_PATH = REPO_ROOT / "docs" / "design" / "agent-spec-interop-2026-07-09.md"
ADAPTERS_PATH = REPO_ROOT / "docs" / "design" / "agent-spec-api" / "14-adapters.md"

CORRECTED_FILES = {
    "02-flows-nodes.md": FLOWS_NODES_PATH,
    "00-master-synthesis.md": MASTER_SYNTHESIS_PATH,
    "agent-spec-interop-2026-07-09.md": INTEROP_PATH,
    "14-adapters.md": ADAPTERS_PATH,
}

# design step 4 explicitly says do NOT edit this file -- confirm it is not
# accidentally part of the corrected-files set this guard checks.
RATIFICATION_FILE = "agent-spec-ratification-2026-07-13.md"

STALE_PATTERNS = (
    "exact lowering TBD",
    "gated edge (exact lowering TBD",
    "exact lowering still TBD",
)

ZERO_PLUMBING_PATTERNS = (
    "zero extra plumbing",
    "zero-extra-plumbing",
)

COERCION_KEYWORDS = (
    "coerc",  # matches coercion / coerce / coercing
)


@pytest.fixture(params=sorted(CORRECTED_FILES.keys()))
def corrected_doc(request) -> tuple[str, str]:
    """Yields (label, text) for each of the four corrected target docs."""
    label = request.param
    path = CORRECTED_FILES[label]
    if not path.exists():
        pytest.fail(f"expected doc not found at {path.relative_to(REPO_ROOT)}")
    return label, path.read_text(encoding="utf-8")


class TestCorrectedFileSetExcludesRatificationRecord:
    """design step 4: docs/design/agent-spec-ratification-2026-07-13.md must NOT
    be part of the corrected-files list -- it's a historical decision record."""

    def test_ratification_file_not_in_corrected_set(self):
        assert RATIFICATION_FILE not in CORRECTED_FILES
        assert not any(
            path.name == RATIFICATION_FILE for path in CORRECTED_FILES.values()
        )


class TestStaleLoweringLanguageRemoved:
    """None of the four target docs may still carry the stale
    'exact lowering TBD' / 'gated edge (exact lowering TBD' language."""

    def test_no_stale_tbd_language_remains(self, corrected_doc: tuple[str, str]):
        label, text = corrected_doc
        for pattern in STALE_PATTERNS:
            assert pattern not in text, (
                f"{label} still contains stale unresolved-lowering language: "
                f"{pattern!r}"
            )


class TestCorrectedCompositeIsNamed:
    """Each doc must name the verified composite: BranchingNode + InputMessageNode.

    (Not every doc necessarily repeats the FULL PAUSE_BRANCH/DEFAULT_BRANCH/
    ControlFlowEdge wiring verbatim -- the master-synthesis row is an
    annotation, not the primary correction site -- but every target file must
    at minimum name both classes so the doc set is internally consistent.)
    """

    def test_doc_names_branching_node(self, corrected_doc: tuple[str, str]):
        label, text = corrected_doc
        assert "BranchingNode" in text, f"{label} must name BranchingNode"

    def test_doc_names_input_message_node(self, corrected_doc: tuple[str, str]):
        label, text = corrected_doc
        assert "InputMessageNode" in text, f"{label} must name InputMessageNode"


class TestFlowsNodesFullCompositeWiring:
    """docs/design/agent-spec-api/02-flows-nodes.md (:22, :132-137) is the primary
    correction site and must carry the FULL verified composite wiring, not just
    the two class names."""

    def test_names_pause_branch_label(self):
        text = FLOWS_NODES_PATH.read_text(encoding="utf-8")
        assert "PAUSE_BRANCH" in text

    def test_names_default_branch_label(self):
        text = FLOWS_NODES_PATH.read_text(encoding="utf-8")
        assert "DEFAULT_BRANCH" in text

    def test_names_control_flow_edge(self):
        text = FLOWS_NODES_PATH.read_text(encoding="utf-8")
        assert "ControlFlowEdge" in text

    def test_names_reconverge(self):
        text = FLOWS_NODES_PATH.read_text(encoding="utf-8")
        assert "reconverge" in text.lower()


class TestInteropFullCompositeWiring:
    """docs/design/agent-spec-interop-2026-07-09.md (:174) must also carry the
    corrected composite target, replacing 'condition → BranchingNode / gated
    edge (exact lowering TBD in impl)'."""

    def test_names_pause_branch_label(self):
        text = INTEROP_PATH.read_text(encoding="utf-8")
        assert "PAUSE_BRANCH" in text

    def test_names_control_flow_edge(self):
        text = INTEROP_PATH.read_text(encoding="utf-8")
        assert "ControlFlowEdge" in text


class TestAdaptersFullCompositeWiring:
    """docs/design/agent-spec-api/14-adapters.md (:142) Export-lowering table row
    must carry the corrected composite target, replacing 'BranchingNode /
    gated edge (exact lowering TBD)'."""

    def test_names_pause_branch_label(self):
        text = ADAPTERS_PATH.read_text(encoding="utf-8")
        assert "PAUSE_BRANCH" in text

    def test_names_control_flow_edge(self):
        text = ADAPTERS_PATH.read_text(encoding="utf-8")
        assert "ControlFlowEdge" in text


class TestNoZeroPlumbingFraming:
    """Architect review MEDIUM finding: the doc must NOT ship 'zero extra
    plumbing'-style framing -- BranchingNode's mapping-key contract requires
    an explicit boolean-to-string-key coercion step that must be stated, not
    hidden behind a 'zero plumbing' claim."""

    def test_doc_does_not_claim_zero_extra_plumbing(
        self, corrected_doc: tuple[str, str]
    ):
        label, text = corrected_doc
        lowered = text.lower()
        for pattern in ZERO_PLUMBING_PATTERNS:
            assert pattern not in lowered, (
                f"{label} must not ship 'zero extra plumbing' framing -- "
                f"the boolean-to-string-key coercion obligation must be "
                f"stated explicitly instead"
            )


class TestCoercionObligationStatedNearCorrection:
    """The boolean-to-string-key coercion obligation (Operator.when yields a
    Python truthy value; BranchingNode's mapping keys are literal strings)
    must be mentioned near the Operator/BranchingNode correction in the
    primary correction site -- omitting it would let the doc imply the
    composite pauses automatically when in fact an unhandled mismatch
    silently always takes DEFAULT_BRANCH (never pauses)."""

    def test_flows_nodes_mentions_coercion_obligation(self):
        text = FLOWS_NODES_PATH.read_text(encoding="utf-8")
        lowered = text.lower()
        assert any(kw in lowered for kw in COERCION_KEYWORDS), (
            "02-flows-nodes.md must state the boolean-to-string-key coercion "
            "obligation near the Operator/BranchingNode correction"
        )

    def test_flows_nodes_mentions_string_key_mapping_contract(self):
        text = FLOWS_NODES_PATH.read_text(encoding="utf-8")
        assert "mapping" in text.lower()
        assert "string" in text.lower()
