"""Introspection-driven Agent Spec export + round-trip COVERAGE MATRIX.

Origin (neograph-sdfgz): the Agent Spec export/round-trip surface produced a
sibling bug on every fix (ozxqw -> qtfof.1/.2/.3 -> hf505 -> 3lk2l). Every one
hid behind the same blind spot: the tests exercised only the shapes a human
remembered to hand-type, so a whole axis (the Oracle ``merge_prompt`` variant,
the entire ``mode`` axis) silently went uncovered.

neograph-00447 removes the human from the completeness loop. The matrix's cell
set is now MECHANICALLY DERIVED from two closed enumerations:

  * pyagentspec's concrete ``flows.nodes.Node`` subclass set -- classified in the
    SHARED ``tests/agent_spec_capabilities.py`` registry (also consumed by the AST
    guard neograph-tjupj), with a completeness assertion that a new primitive
    fails loud.
  * neograph's own introspected axes:
        Node.mode Literal                     (typing.get_args)
      x supported ModifierCombo subset        (partition-asserted vs the enum)
      x Oracle merge_fn XOR merge_prompt       (read off Oracle.model_fields)
      x input shape {single, dict, +context}

The cross product is generated by ``_generate_cells``; ``CELLS`` is that generated
dict, NOT a hand-typed list. Every generated cell is classified into exactly one
of three buckets by an EXPLICIT literal set, and a LOUD partition assertion
requires the three buckets to union to the full generated set -- so a NEW axis
(a mode, a combo, an oracle config) forces classification instead of silently
under-covering:

  * GREEN            -- builds, exports, and round-trips cleanly.
  * RED_EXPORT       -- builds, but ``to_agent_spec`` raises today; the agent-spec
                        gap neograph-i7k7j will fix. Marked ``xfail(strict=True)``
                        so a fix XPASSes -> fails -> ratchets i7k7j.
  * UNREPRESENTABLE  -- neograph's OWN construct assembly rejects the combination
                        (agent/act Each/Loop over multiple upstream inputs). This
                        is the north-star "you can't write it" guarantee, NOT an
                        agent-spec bug, and is NOT handed to i7k7j. The matrix
                        asserts the build raises.

The two root-cause families the GREEN cells still pin (neograph-sdfgz):
  (A) dict-form title/property mapping in ``to_agent_spec``'s DataFlowEdge wiring
      -- an Each-modified (MapNode) destination needs ``iterated_``-prefixed
      inputs, and its sub-flow StartNode must declare them (neograph-hf505).
  (B) type-identity loss on round-trip -- the fan-out receiver of a primary
      ``@node(map_over=)`` node must reconstruct to the SAME structural type as
      the producer's list element (neograph-3lk2l / qtfof.4 / wqb5t).

Run with::

    uv run --extra dev --extra agent-spec pytest tests/test_agent_spec_matrix.py
"""

from __future__ import annotations

import typing

import pytest
from pydantic import BaseModel

pytest.importorskip("pyagentspec")

from neograph import Construct, ConstructError, Tool, node  # noqa: E402
from neograph._agent_spec import to_agent_spec  # noqa: E402
from neograph.decorators import construct_from_functions  # noqa: E402
from neograph.loader import from_agent_spec  # noqa: E402
from neograph.modifiers import ModifierCombo, Oracle  # noqa: E402
from neograph.node import Node  # noqa: E402
from tests.agent_spec_capabilities import assert_registry_complete  # noqa: E402
from tests.fakes import register_scripted  # noqa: E402

# -- Shared models -----------------------------------------------------------


class Alpha(BaseModel, frozen=True):
    a: str


class Beta(BaseModel, frozen=True):
    b: str


class Ctx(BaseModel, frozen=True):
    c: str


class Elem(BaseModel, frozen=True):
    v: str


class Coll(BaseModel, frozen=True):
    groups: list[Elem]


class Out(BaseModel, frozen=True):
    ok: str


# -- Closed axes, introspected (never hand-typed) ----------------------------

# Axis 1 -- modes: the closed Literal. 'raw' is intentionally NOT here -- it is
# raw_fn-set, not a mode value, and is rejected pre-lowering.
MODES: tuple[str, ...] = typing.get_args(Node.model_fields["mode"].annotation)

# Axis 2 -- per-node modifier combos. The two sets are EXPLICIT (architect
# review M1): a loud partition vs ModifierCombo forces classification of any new
# combo. SUPPORTED = what ``_lower_construct_item`` lowers per node; UNSUPPORTED =
# PORTAL (lowered at construct level, not per node) + every fusion combo that
# raises ConfigurationError.
SUPPORTED_COMBOS: frozenset[ModifierCombo] = frozenset(
    {
        ModifierCombo.BARE,
        ModifierCombo.EACH,
        ModifierCombo.ORACLE,
        ModifierCombo.LOOP,
        ModifierCombo.OPERATOR,
    }
)
UNSUPPORTED_COMBOS: frozenset[ModifierCombo] = frozenset(
    {
        ModifierCombo.ORACLE_OPERATOR,
        ModifierCombo.EACH_OPERATOR,
        ModifierCombo.EACH_ORACLE,
        ModifierCombo.EACH_ORACLE_OPERATOR,
        ModifierCombo.LOOP_OPERATOR,
        ModifierCombo.PORTAL,
        ModifierCombo.PORTAL_OPERATOR,
    }
)

# Axis 3 -- Oracle config discriminator. The XOR pair is named here but VALIDATED
# against Oracle.model_fields (fails loud if either field is renamed rather than
# copy-typing a name the model no longer has). NOTE (residual drift, architect
# review LOW): a future THIRD mutually-exclusive merge_* variant added to Oracle's
# validator (modifiers.py) would NOT be auto-picked-up here -- re-derive from the
# validator if a third variant ever lands.
ORACLE_CONFIGS: tuple[str, ...] = ("merge_fn", "merge_prompt")
assert set(ORACLE_CONFIGS) <= set(Oracle.model_fields), (
    "Oracle merge_fn/merge_prompt XOR pair renamed; update ORACLE_CONFIGS from "
    f"Oracle.model_fields ({sorted(Oracle.model_fields)})"
)

# Axis 4 -- input shapes. Each additionally carries a non-fan-out "context".
SHAPES: tuple[str, ...] = ("single", "dict")


# -- Generic cell builder ----------------------------------------------------
#
# ONE builder for the whole cross product. The (mode, combo, config, shape)
# tuple fully determines the @node kwargs and the prompt content:
#
#   mode      -> scripted: no prompt/model (body-run node)
#                think:    mode/model/prompt (LLM, no tools)
#                agent:    + read tool          act: + write tool
#                LLM prompts reference their inputs via ${...}; this is what
#                triggers _check_placeholder_inputs (and is why every LLM-mode
#                cell WITH inputs is RED today -- dotted @node titles can't be
#                expressed as jinja placeholders).
#   combo     -> the modifier kwarg(s): map_over= (Each), ensemble_n+merge (Oracle),
#                loop_when+max_iterations (Loop), interrupt_when (Operator).
#   config    -> Oracle only: merge_fn="m_combine" vs merge_prompt=<template>.
#   shape     -> single: one upstream input; dict: two upstream inputs (fan-in);
#                context: Each fan-out receiver + a non-fan-out context input.


def _input_refs(combo: ModifierCombo, shape: str) -> str:
    """The ``${path}`` references an LLM-mode cell's prompt must contain so Option F
    (neograph-cbpyx) can translate them to ``{{ flat }}`` placeholders. Every
    declared input is referenced (an input a prompt never mentions is dropped from
    the exported primitive), and the paths are the REAL dotted @node input titles
    (``{param}.{field}``), not the old generic ``${x}`` (which named no declared
    input and could never turn a cell green)."""
    if combo is ModifierCombo.EACH:
        if shape == "single":
            return "${item.v}"
        if shape == "dict":
            return "${item.v} ${pb.b}"
        return "${source.c} ${item.v}"  # context
    # BARE / ORACLE / LOOP / OPERATOR
    if shape == "single":
        return "${prod.a}"
    return "${pa.a} ${pb.b}"


def _llm_kwargs(mode: str, combo: ModifierCombo, shape: str) -> dict[str, object]:
    """@node kwargs that select the execution mode; scripted adds none. The prompt
    references the cell's REAL declared inputs (via ``_input_refs``) so Option F
    translates them -- Oracle's merge_prompt template is set separately in the
    ORACLE branch (it references the variant output ``${ok}``, not the inputs)."""
    if mode == "scripted":
        return {}
    kw: dict[str, object] = {"mode": mode, "model": "fast", "prompt": f"process {_input_refs(combo, shape)}"}
    if mode == "agent":
        kw["tools"] = [Tool(name="t_read", budget=1)]
    if mode == "act":
        kw["tools"] = [Tool(name="t_write", budget=1)]
    return kw


def _cell_id(mode: str, combo: ModifierCombo, config: str | None, shape: str) -> str:
    base = combo.name.lower()
    if config is not None:
        return f"{mode}-{base}-{config}-{shape}"
    return f"{mode}-{base}-{shape}"


def build_cell(mode: str, combo: ModifierCombo, config: str | None, shape: str) -> Construct:
    """Build a fresh Construct for one (mode, combo, config, shape) cell.

    Any condition / merge referenced by a modifier is registered inside the
    builder because conftest's autouse fixture resets every registry per test.
    """
    lk = _llm_kwargs(mode, combo, shape)
    nm = _cell_id(mode, combo, config, shape)

    if combo is ModifierCombo.BARE:
        if shape == "single":

            @node(outputs=Alpha)
            def prod() -> Alpha: ...

            @node(outputs=Out, **lk)
            def target(prod: Alpha) -> Out: ...

            return construct_from_functions(nm, [prod, target])

        @node(outputs=Alpha)
        def pa() -> Alpha: ...

        @node(outputs=Beta)
        def pb() -> Beta: ...

        @node(outputs=Out, **lk)
        def target(pa: Alpha, pb: Beta) -> Out: ...

        return construct_from_functions(nm, [pa, pb, target])

    if combo is ModifierCombo.EACH:

        @node(outputs=Coll)
        def prod() -> Coll: ...

        if shape == "single":

            @node(outputs=Out, map_over="prod.groups", map_key="v", **lk)
            def target(item: Elem) -> Out: ...

            return construct_from_functions(nm, [prod, target])

        if shape == "dict":

            @node(outputs=Beta)
            def pb() -> Beta: ...

            @node(outputs=Out, map_over="prod.groups", map_key="v", **lk)
            def target(item: Elem, pb: Beta) -> Out: ...

            return construct_from_functions(nm, [prod, pb, target])

        # context

        @node(outputs=Ctx)
        def source() -> Ctx: ...

        @node(outputs=Out, map_over="prod.groups", map_key="v", **lk)
        def target(source: Ctx, item: Elem) -> Out: ...

        return construct_from_functions(nm, [prod, source, target])

    if combo is ModifierCombo.ORACLE:
        register_scripted("m_combine", lambda variants, config: variants[0])
        oracle_kw: dict[str, object] = {"ensemble_n": 2}
        if config == "merge_fn":
            oracle_kw["merge_fn"] = "m_combine"
        else:
            # merge_prompt references the variant OUTPUT (gen node outputs=Out -> the
            # single-type bare title 'ok'), so Option F translates ${ok} -> {{ ok }}
            # and routes the variant->merge fan-in edge through that flat name.
            oracle_kw["merge_prompt"] = "combine ${ok}"

        if shape == "single":

            @node(outputs=Alpha)
            def prod() -> Alpha: ...

            @node(outputs=Out, **oracle_kw, **lk)
            def gen(prod: Alpha) -> Out: ...

            return construct_from_functions(nm, [prod, gen])

        @node(outputs=Alpha)
        def pa() -> Alpha: ...

        @node(outputs=Beta)
        def pb() -> Beta: ...

        @node(outputs=Out, **oracle_kw, **lk)
        def gen(pa: Alpha, pb: Beta) -> Out: ...

        return construct_from_functions(nm, [pa, pb, gen])

    if combo is ModifierCombo.LOOP:
        # Expression condition (the documented serialization target and the shape
        # the passing round-trip cells use); condition references field ``a`` so
        # the loop node output stays Alpha.
        if shape == "single":

            @node(outputs=Alpha)
            def prod() -> Alpha: ...

            @node(outputs=Alpha, loop_when='a == "x"', max_iterations=3, **lk)
            def refine(prod: Alpha) -> Alpha: ...

            return construct_from_functions(nm, [prod, refine])

        @node(outputs=Alpha)
        def pa() -> Alpha: ...

        @node(outputs=Beta)
        def pb() -> Beta: ...

        @node(outputs=Alpha, loop_when='a == "x"', max_iterations=3, **lk)
        def refine(pa: Alpha, pb: Beta) -> Alpha: ...

        return construct_from_functions(nm, [pa, pb, refine])

    if combo is ModifierCombo.OPERATOR:
        if shape == "single":

            @node(outputs=Alpha)
            def prod() -> Alpha: ...

            @node(outputs=Alpha, interrupt_when='a == "x"', **lk)
            def review(prod: Alpha) -> Alpha: ...

            return construct_from_functions(nm, [prod, review])

        @node(outputs=Alpha)
        def pa() -> Alpha: ...

        @node(outputs=Beta)
        def pb() -> Beta: ...

        @node(outputs=Alpha, interrupt_when='a == "x"', **lk)
        def review(pa: Alpha, pb: Beta) -> Alpha: ...

        return construct_from_functions(nm, [pa, pb, review])

    raise AssertionError(f"unhandled combo {combo}")  # pragma: no cover


def _generate_cells() -> dict[str, tuple[str, ModifierCombo, str | None, str]]:
    """Mechanically derive the full cell set from the introspected closed axes.

    Restricted to what ``_agent_spec.py``'s per-node dispatch claims to support
    (``SUPPORTED_COMBOS``). ORACLE additionally crosses the merge_fn/merge_prompt
    config AND the input shape (architect review M3); EACH adds a ``context``
    shape.
    """
    cells: dict[str, tuple[str, ModifierCombo, str | None, str]] = {}
    for mode in MODES:
        for combo in SUPPORTED_COMBOS:
            if combo is ModifierCombo.ORACLE:
                for cfg in ORACLE_CONFIGS:
                    for shape in SHAPES:
                        cid = _cell_id(mode, combo, cfg, shape)
                        cells[cid] = (mode, combo, cfg, shape)
            elif combo is ModifierCombo.EACH:
                for shape in (*SHAPES, "context"):
                    cid = _cell_id(mode, combo, None, shape)
                    cells[cid] = (mode, combo, None, shape)
            else:  # BARE / LOOP / OPERATOR
                for shape in SHAPES:
                    cid = _cell_id(mode, combo, None, shape)
                    cells[cid] = (mode, combo, None, shape)
    return cells


CELLS: dict[str, tuple[str, ModifierCombo, str | None, str]] = _generate_cells()


# -- Per-cell expected outcome (EXPLICIT literal partition) -------------------
#
# Every generated cell is classified by an explicit literal set. The partition
# assertion (TestAgentSpecMatrixExhaustiveness) requires GREEN | RED_EXPORT |
# UNREPRESENTABLE == set(CELLS), so a new axis-derived cell that nobody
# classified fails loud. Membership is the CURRENT observed behavior at HEAD
# (neograph-00447 probe); do NOT "fix" a RED cell here -- that is neograph-i7k7j.

# Builds, exports, and round-trips cleanly. Since Option F (neograph-cbpyx), every
# LLM-mode (think/agent/act) cell whose prompt references its real inputs via
# ${path} exports too: the translator rewrites ${prod.a} -> {{ prod_a }} and the
# consumer sweep (input edges, Loop self-edge, Oracle fan-in, Each StartNode) routes
# every destination_input through the SAME flat name. The ONLY remaining RED_EXPORT
# cells are Oracle+agent/act (no lowering yet -- neograph-i7k7j); Oracle+think and
# Oracle merge_prompt (scripted+think) are now GREEN.
GREEN: frozenset[str] = frozenset(
    {
        # scripted (LLM-free ToolNode lowerings; green pre-Option-F)
        "scripted-bare-single",
        "scripted-bare-dict",
        "scripted-each-single",
        "scripted-each-dict",
        "scripted-each-context",
        "scripted-loop-single",
        "scripted-loop-dict",
        "scripted-operator-single",
        "scripted-operator-dict",
        "scripted-oracle-merge_fn-single",
        "scripted-oracle-merge_fn-dict",
        # scripted Oracle merge_prompt (translated merge LlmNode) -- green via Option F
        "scripted-oracle-merge_prompt-single",
        "scripted-oracle-merge_prompt-dict",
        # think -- all green via Option F
        "think-bare-single",
        "think-bare-dict",
        "think-each-single",
        "think-each-dict",
        "think-each-context",
        "think-loop-single",
        "think-loop-dict",
        "think-operator-single",
        "think-operator-dict",
        "think-oracle-merge_fn-single",
        "think-oracle-merge_fn-dict",
        "think-oracle-merge_prompt-single",
        "think-oracle-merge_prompt-dict",
        # agent -- BARE/EACH-single/LOOP-single/OPERATOR green via Option F
        # (each-dict/context + loop-dict are UNREPRESENTABLE; oracle stays RED)
        "agent-bare-single",
        "agent-bare-dict",
        "agent-each-single",
        "agent-loop-single",
        "agent-operator-single",
        "agent-operator-dict",
        # act -- same shape as agent
        "act-bare-single",
        "act-bare-dict",
        "act-each-single",
        "act-loop-single",
        "act-operator-single",
        "act-operator-dict",
    }
)

# neograph's OWN construct assembly rejects these: an Each/Loop over an agent/act
# node with multiple upstream inputs is unrepresentable (the north-star "you
# can't write it" guarantee). NOT an agent-spec gap; NOT handed to i7k7j.
UNREPRESENTABLE: frozenset[str] = frozenset(
    {
        "agent-each-dict",
        "agent-each-context",
        "agent-loop-dict",
        "act-each-dict",
        "act-each-context",
        "act-loop-dict",
    }
)

# Everything else builds but ``to_agent_spec`` raises today -- the agent-spec
# export gap neograph-i7k7j owns. Derived (not hand-listed) so it can't drift out
# of sync with the generated set or the two explicit buckets above.
RED_EXPORT: frozenset[str] = frozenset(CELLS) - GREEN - UNREPRESENTABLE

_I7K7J_BLOCKER = (
    "neograph-i7k7j: Oracle+agent/act lowering not yet implemented -- _lower_oracle "
    "raises for agent/act-mode variants (_agent_spec.py, 'Oracle+agent/act export has "
    "no Agent Spec lowering yet'). NOT placeholder coupling (Option F / neograph-cbpyx "
    "translated every think/scripted Oracle + LLM-mode cell to GREEN)."
)

# The prior hand-typed CELLS keys, expressed in the derived scheme. An EXPLICIT
# literal (independent of _generate_cells) so the coverage check is a TRUE
# superset assertion, not a vacuous same-function tautology (architect review
# M3). If the generator ever stops producing one of these, the assertion fails.
_PRIOR_GREEN_CELL_IDS: frozenset[str] = frozenset(
    {
        "scripted-bare-single",  # was none-single
        "scripted-bare-dict",  # was none-dict
        "scripted-each-single",
        "scripted-each-context",
        "scripted-oracle-merge_fn-single",  # was oracle-single
        "scripted-oracle-merge_fn-dict",  # was oracle-dict
        "scripted-loop-single",
        "scripted-operator-single",
    }
)


class TestAgentSpecMatrixExhaustiveness:
    """The matrix must be MECHANICALLY DERIVED from the closed enumerations, and
    every generated cell must be explicitly classified (neograph-00447)."""

    def test_pyagentspec_registry_is_complete(self) -> None:
        """The shared node-family registry must cover every concrete pyagentspec
        primitive -- a new one fails loud (step 1)."""
        assert_registry_complete()

    def test_modifier_combo_axis_is_a_loud_partition(self) -> None:
        """A new ModifierCombo member forces classification into supported vs
        unsupported (architect review M1) -- it cannot silently go uncovered."""
        assert SUPPORTED_COMBOS.isdisjoint(UNSUPPORTED_COMBOS)
        assert SUPPORTED_COMBOS | UNSUPPORTED_COMBOS == set(ModifierCombo), (
            "ModifierCombo has member(s) classified as neither SUPPORTED nor "
            f"UNSUPPORTED: {set(ModifierCombo) - SUPPORTED_COMBOS - UNSUPPORTED_COMBOS}. "
            "Classify every combo so the per-node cross product stays exhaustive."
        )

    def test_every_generated_cell_is_classified(self) -> None:
        """GREEN | RED_EXPORT | UNREPRESENTABLE must partition the generated set
        exactly -- a new mode/combo/config axis surfaces cells that force
        classification instead of silently under-covering (the sdfgz disease)."""
        assert GREEN.isdisjoint(UNREPRESENTABLE)
        union = GREEN | RED_EXPORT | UNREPRESENTABLE
        assert union == set(CELLS), (
            "generated cells not covered by an explicit bucket: "
            f"{set(CELLS) - union}; buckets over-reaching the generated set: "
            f"{union - set(CELLS)}"
        )

    def test_prior_green_cells_are_still_generated_and_green(self) -> None:
        """The 8 originally hand-typed cells must still be produced by the
        generator AND still classified GREEN (true coverage check, not a
        same-function tautology -- architect review M3)."""
        missing = _PRIOR_GREEN_CELL_IDS - set(CELLS)
        assert not missing, f"generator dropped prior cells: {sorted(missing)}"
        regressed = _PRIOR_GREEN_CELL_IDS - GREEN
        assert not regressed, f"prior GREEN cells no longer GREEN: {sorted(regressed)}"

    def test_oracle_axis_crosses_config_and_shape(self) -> None:
        """Oracle must be crossed with BOTH merge_fn/merge_prompt AND single/dict
        (the axis that let the merge_prompt cell escape -- architect review M3)."""
        for cfg in ORACLE_CONFIGS:
            for shape in SHAPES:
                assert f"scripted-oracle-{cfg}-{shape}" in CELLS


# -- The matrix --------------------------------------------------------------


class TestAgentSpecExportMatrix:
    """Every derived cell either exports to a valid Flow (GREEN), is a known
    export gap (RED_EXPORT -> xfail), or is unrepresentable in neograph."""

    @pytest.mark.parametrize("cell_id", sorted(CELLS))
    def test_export(self, cell_id: str, request: pytest.FixtureRequest) -> None:
        mode, combo, config, shape = CELLS[cell_id]

        if cell_id in UNREPRESENTABLE:
            # north-star: neograph rejects the construct at assembly time.
            with pytest.raises(ConstructError):
                build_cell(mode, combo, config, shape)
            return

        if cell_id in RED_EXPORT:
            request.node.add_marker(pytest.mark.xfail(reason=_I7K7J_BLOCKER, strict=True))

        construct = build_cell(mode, combo, config, shape)
        # Must not raise (hf505: Each + context input raised a pydantic
        # DataFlowEdge ValidationError here).
        flow = to_agent_spec(construct)
        assert flow is not None
        assert flow.nodes


class TestAgentSpecRoundTripMatrix:
    """Every GREEN cell must ROUND-TRIP: export then re-import into a valid
    Construct (from_agent_spec runs assembly validation, where 3lk2l's Each
    element-type mismatch was raised). RED_EXPORT cells fail at export already
    (xfail); UNREPRESENTABLE cells never build."""

    @pytest.mark.parametrize("cell_id", sorted(CELLS))
    def test_round_trip(self, cell_id: str, request: pytest.FixtureRequest) -> None:
        mode, combo, config, shape = CELLS[cell_id]

        if cell_id in UNREPRESENTABLE:
            with pytest.raises(ConstructError):
                build_cell(mode, combo, config, shape)
            return

        if cell_id in RED_EXPORT:
            request.node.add_marker(pytest.mark.xfail(reason=_I7K7J_BLOCKER, strict=True))

        construct = build_cell(mode, combo, config, shape)
        flow = to_agent_spec(construct)
        imported = from_agent_spec(flow)
        assert isinstance(imported, Construct)
        assert imported.nodes
