"""neograph.testing — auto-scaffolded test suites from pipeline definitions.

Introspects a Construct and generates a pytest-compatible test file with
stubs for every node, edge, sub-construct, and the full pipeline.

Three test levels:
    1. Per-node: scripted nodes get run_isolated() stubs, LLM nodes get
       metadata assertions. Each has a fixture stub for test data.
    2. Per-sub-construct: compile + run with fixtures.
    3. Per-construct: topology checks, compilation smoke, full E2E.

Usage:
    # CLI
    neograph test-scaffold my_pipeline.py --output tests/test_my_pipeline.py

    # Programmatic
    from neograph.testing import scaffold_tests
    scaffold_tests(my_construct, output_path="tests/test_my_pipeline.py")

Generated tests fail by default (pytest.fail, not skip) until implemented.
A sync meta-test catches drift between the construct and the test file.
"""

from __future__ import annotations

import os
import textwrap
from typing import Any

from neograph.construct import Construct
from neograph.naming import field_name_for
from neograph.node import Node


def _node_info(node: Node) -> dict[str, Any]:
    """Extract test-relevant metadata from a node."""
    inputs_dict = node.inputs if isinstance(node.inputs, dict) else {}
    outputs_name = (
        node.outputs.__name__
        if hasattr(node.outputs, "__name__")
        else repr(node.outputs)
    )
    return {
        "name": node.name,
        "field": field_name_for(node.name),
        "mode": node.mode,
        "outputs": node.outputs,
        "outputs_name": outputs_name,
        "inputs_dict": inputs_dict,
        "is_scripted": node.mode == "scripted",
        "is_llm": node.mode in ("think", "agent", "act"),
        "has_oracle": node.modifier_set.oracle is not None,
        "has_each": node.modifier_set.each is not None,
        "has_loop": node.modifier_set.loop is not None,
        "prompt": node.prompt,
        "model": node.model,
    }


def _collect_nodes(construct: Construct) -> list[dict[str, Any]]:
    """Collect node info from a construct, including sub-constructs."""
    nodes = []
    for item in construct.nodes:
        if isinstance(item, Node):
            nodes.append(_node_info(item))
        elif isinstance(item, Construct):
            # Sub-construct: record as a unit, also recurse
            nodes.append({
                "name": item.name,
                "field": field_name_for(item.name),
                "is_subconstruct": True,
                "input_name": item.input.__name__ if item.input else "None",
                "output_name": item.output.__name__ if item.output else "None",
            })
    return nodes


def _collect_edges(construct: Construct) -> list[tuple[str, str]]:
    """Collect declared edges (upstream → downstream) from the construct."""
    edges = []
    for item in construct.nodes:
        if not isinstance(item, Node):
            continue
        if isinstance(item.inputs, dict):
            for upstream_name in item.inputs:
                edges.append((upstream_name, field_name_for(item.name)))
    return edges


def scaffold_tests(
    construct: Construct,
    output_path: str,
    *,
    construct_import: str | None = None,
    overwrite: bool = False,
) -> str:
    """Generate a pytest test file from a Construct definition.

    Args:
        construct: The pipeline construct to scaffold tests for.
        output_path: Where to write the generated test file.
        construct_import: Python import path for the construct
            (e.g., "my_app.pipelines.rw_ingestion"). If None, uses a placeholder.
        overwrite: If True, overwrite existing file. Default False (refuse).

    Returns:
        The generated test file content.
    """
    if os.path.exists(output_path) and not overwrite:
        raise FileExistsError(
            f"{output_path} already exists. Use overwrite=True or delete it first."
        )

    nodes = _collect_nodes(construct)
    edges = _collect_edges(construct)
    real_nodes = [n for n in nodes if not n.get("is_subconstruct")]
    sub_constructs = [n for n in nodes if n.get("is_subconstruct")]
    scripted = [n for n in real_nodes if n.get("is_scripted")]
    llm_nodes = [n for n in real_nodes if n.get("is_llm")]

    import_line = construct_import or f"# TODO: import your construct here"
    construct_var = field_name_for(construct.name)

    lines: list[str] = []

    # Header
    lines.append(f'"""Auto-scaffolded tests for construct \'{construct.name}\'.')
    lines.append("")
    lines.append(f"Generated by neograph.testing.scaffold_tests().")
    lines.append(f"Nodes: {len(real_nodes)} | Sub-constructs: {len(sub_constructs)} | Edges: {len(edges)}")
    lines.append("")
    lines.append("Tests marked with pytest.fail('TODO') need implementation.")
    lines.append("The sync test at the bottom catches drift when nodes are added/removed.")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import pytest")
    lines.append("")
    if construct_import:
        lines.append(f"from {construct_import} import {construct_var}")
    else:
        lines.append(f"# {import_line}")
        lines.append(f"# {construct_var} = ...  # your construct")
    lines.append("")
    lines.append("")

    # ── Section 1: Topology ──────────────────────────────────────────
    lines.append("# " + "=" * 70)
    lines.append("# TOPOLOGY — auto-verified, no human input needed")
    lines.append("# " + "=" * 70)
    lines.append("")
    lines.append("")
    lines.append("class TestTopology:")
    lines.append(f'    """Construct \'{construct.name}\' structural invariants."""')
    lines.append("")
    lines.append(f"    def test_node_count(self):")
    lines.append(f'        """Construct has exactly {len(construct.nodes)} nodes."""')
    lines.append(f"        assert len({construct_var}.nodes) == {len(construct.nodes)}")
    lines.append("")

    # All nodes present
    lines.append(f"    def test_all_nodes_present(self):")
    lines.append(f'        """Every declared node exists in the construct."""')
    lines.append(f"        names = [n.name for n in {construct_var}.nodes]")
    for n in nodes:
        lines.append(f'        assert "{n["name"]}" in names')
    lines.append("")

    # Topological ordering per edge
    if edges:
        lines.append(f"    def test_topological_ordering(self):")
        lines.append(f'        """Upstream nodes appear before their consumers."""')
        lines.append(f"        names = [getattr(n, 'name', '') for n in {construct_var}.nodes]")
        for upstream, downstream in edges:
            up_name = upstream.replace("_", "-")
            down_name = downstream.replace("_", "-")
            lines.append(
                f'        assert names.index("{up_name}") < names.index("{down_name}"), '
                f'"{up_name} must precede {down_name}"'
            )
        lines.append("")

    # Compilation
    lines.append(f"    def test_compiles(self):")
    lines.append(f'        """Construct compiles to a LangGraph StateGraph."""')
    lines.append(f"        from neograph import compile")
    lines.append(f"        # TODO: configure_llm if construct has LLM nodes")
    if llm_nodes:
        lines.append(f"        # This construct has {len(llm_nodes)} LLM node(s) — configure_llm required")
        lines.append(f'        pytest.fail("TODO: configure_llm and compile")')
    else:
        lines.append(f"        graph = compile({construct_var})")
        lines.append(f"        assert graph is not None")
    lines.append("")
    lines.append("")

    # ── Section 2: Per-node metadata (LLM nodes) ────────────────────
    if llm_nodes:
        lines.append("# " + "=" * 70)
        lines.append("# NODE METADATA — auto-verified for LLM nodes")
        lines.append("# " + "=" * 70)
        lines.append("")
        lines.append("")
        lines.append("class TestNodeMetadata:")
        lines.append(f'    """Output types, modes, and prompts for LLM nodes."""')
        lines.append("")

        for n in llm_nodes:
            fname = n["field"]
            lines.append(f"    def test_{fname}_outputs(self):")
            lines.append(f'        """Node \'{n["name"]}\' produces {n["outputs_name"]}."""')
            lines.append(f"        from {construct_import or 'YOUR_MODULE'} import {fname}")
            lines.append(f"        assert {fname}.outputs is {n['outputs_name']}")
            lines.append("")
            lines.append(f"    def test_{fname}_mode(self):")
            lines.append(f'        """Node \'{n["name"]}\' uses mode=\'{n["mode"]}\'."""')
            lines.append(f"        from {construct_import or 'YOUR_MODULE'} import {fname}")
            lines.append(f'        assert {fname}.mode == "{n["mode"]}"')
            lines.append("")

        lines.append("")

    # ── Section 3: Per-node unit tests (scripted) ────────────────────
    if scripted:
        lines.append("# " + "=" * 70)
        lines.append("# NODE UNIT TESTS — scripted nodes, human provides fixtures")
        lines.append("# " + "=" * 70)
        lines.append("")
        lines.append("")
        lines.append("class TestScriptedNodes:")
        lines.append(f'    """Unit tests for scripted nodes via run_isolated()."""')
        lines.append("")

        for n in scripted:
            fname = n["field"]
            lines.append(f"    def test_{fname}_produces_{n['outputs_name'].lower()}(self):")
            lines.append(f'        """Node \'{n["name"]}\' produces {n["outputs_name"]}."""')
            lines.append(f"        from {construct_import or 'YOUR_MODULE'} import {fname}")

            if n["inputs_dict"]:
                input_keys = list(n["inputs_dict"].keys())
                lines.append(f"        # Inputs: {', '.join(input_keys)}")
                lines.append(f"        # input_data = ...  # TODO: provide {input_keys[0]} fixture")
                lines.append(f"        # result = {fname}.run_isolated(input=input_data)")
                lines.append(f"        # assert isinstance(result, {n['outputs_name']})")
            else:
                lines.append(f"        # result = {fname}.run_isolated()")
                lines.append(f"        # assert isinstance(result, {n['outputs_name']})")

            lines.append(f'        pytest.fail("TODO: provide fixture and implement")')
            lines.append("")

        lines.append("")

    # ── Section 4: Per-node unit tests (LLM — fake response stubs) ──
    if llm_nodes:
        lines.append("# " + "=" * 70)
        lines.append("# LLM NODE STUBS — human provides fake responses")
        lines.append("# " + "=" * 70)
        lines.append("")
        lines.append("")
        lines.append("class TestLLMNodes:")
        lines.append(f'    """LLM node tests with fake responses."""')
        lines.append("")
        lines.append(f"    # Fake response registry — fill in realistic test data:")
        lines.append(f"    # FAKE_RESPONSES = {{")
        for n in llm_nodes:
            lines.append(f'    #     "{n["name"]}": {n["outputs_name"]}(...),  # TODO')
        lines.append(f"    # }}")
        lines.append("")

        for n in llm_nodes:
            fname = n["field"]
            lines.append(f"    def test_{fname}_with_fake_llm(self):")
            lines.append(f'        """Node \'{n["name"]}\' produces {n["outputs_name"]} with fake LLM."""')
            lines.append(f'        pytest.fail("TODO: configure fake LLM, compile, run_isolated or full pipeline")')
            lines.append("")

        lines.append("")

    # ── Section 5: Sub-construct tests ───────────────────────────────
    if sub_constructs:
        lines.append("# " + "=" * 70)
        lines.append("# SUB-CONSTRUCT TESTS")
        lines.append("# " + "=" * 70)
        lines.append("")
        lines.append("")
        lines.append("class TestSubConstructs:")
        lines.append(f'    """Sub-construct compilation and integration."""')
        lines.append("")

        for sc in sub_constructs:
            fname = sc["field"]
            lines.append(f"    def test_{fname}_compiles(self):")
            lines.append(f'        """Sub-construct \'{sc["name"]}\' (input={sc["input_name"]}, output={sc["output_name"]}) compiles."""')
            lines.append(f'        pytest.fail("TODO: compile sub-construct")')
            lines.append("")
            lines.append(f"    def test_{fname}_e2e(self):")
            lines.append(f'        """Sub-construct \'{sc["name"]}\' runs end-to-end with fixtures."""')
            lines.append(f'        pytest.fail("TODO: provide {sc["input_name"]} fixture, run, assert {sc["output_name"]}")')
            lines.append("")

        lines.append("")

    # ── Section 6: E2E ───────────────────────────────────────────────
    lines.append("# " + "=" * 70)
    lines.append("# END-TO-END — full pipeline with all fixtures")
    lines.append("# " + "=" * 70)
    lines.append("")
    lines.append("")
    lines.append("class TestEndToEnd:")
    lines.append(f'    """Full pipeline E2E with fake LLM."""')
    lines.append("")
    lines.append(f"    def test_full_pipeline_runs(self):")
    lines.append(f'        """Compile and run \'{construct.name}\' end-to-end."""')
    lines.append(f'        pytest.fail("TODO: configure_llm, compile, run, assert outputs")')
    lines.append("")
    lines.append("")

    # ── Section 7: Sync meta-test ────────────────────────────────────
    lines.append("# " + "=" * 70)
    lines.append("# SYNC — catches drift between construct and tests")
    lines.append("# " + "=" * 70)
    lines.append("")
    lines.append("")
    lines.append("class TestSync:")
    lines.append(f'    """Ensure this test file stays in sync with the construct."""')
    lines.append("")
    lines.append(f"    EXPECTED_NODES = {{")
    for n in nodes:
        lines.append(f'        "{n["name"]}",')
    lines.append(f"    }}")
    lines.append("")
    lines.append(f"    def test_no_untested_nodes(self):")
    lines.append(f'        """Every node in the construct has a corresponding test."""')
    lines.append(f"        actual = {{")
    lines.append(f"            getattr(n, 'name', getattr(n, 'name', '?'))")
    lines.append(f"            for n in {construct_var}.nodes")
    lines.append(f"        }}")
    lines.append(f"        missing = actual - self.EXPECTED_NODES")
    lines.append(f"        assert not missing, (")
    lines.append(f'            f"{{len(missing)}} node(s) added to construct but not to tests: {{sorted(missing)}}. "')
    lines.append(f'            f"Run: neograph test-scaffold ... --update"')
    lines.append(f"        )")
    lines.append("")
    lines.append(f"    def test_no_stale_tests(self):")
    lines.append(f'        """No tests reference nodes that were removed from the construct."""')
    lines.append(f"        actual = {{")
    lines.append(f"            getattr(n, 'name', getattr(n, 'name', '?'))")
    lines.append(f"            for n in {construct_var}.nodes")
    lines.append(f"        }}")
    lines.append(f"        stale = self.EXPECTED_NODES - actual")
    lines.append(f"        assert not stale, (")
    lines.append(f'            f"{{len(stale)}} node(s) removed from construct but still in tests: {{sorted(stale)}}. "')
    lines.append(f'            f"Remove their test stubs."')
    lines.append(f"        )")
    lines.append("")

    content = "\n".join(lines)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(content)

    return content
